PRBS generator wrapper for system identification
lnls-dig/infra-cores pull request #15
Opened 2023-03-29 19:43 UTC by guilhermerc

2023-03-29 20:29 UTC, Palmitoxico requested changes

2023-03-29 20:29 UTC, Palmitoxico commented on modules/common/prbs_for_sys_id/prbs_gen_for_sys_id.vhd
> +          when EXTEND_PRBS_BIT =>
This state name `EXTEND_PRBS_BIT` is confusing. Use something like `WAIT_STEP_DURATION`.

2023-03-29 20:29 UTC, Palmitoxico commented on modules/common/prbs_for_sys_id/prbs_gen_for_sys_id.vhd
> +  inst_prbs_gen : entity work.prbs_gen
Use component declaration here to keep consistency with other cores. Remember to add `prbs_gen` component to [ifc_common_pkg.vhd](https://github.com/lnls-dig/infra-cores/blob/master/modules/common/ifc_common_pkg.vhd).

2023-03-29 20:29 UTC, Palmitoxico commented on testbench/common/prbs_gen_for_sys_id_tb/Manifest.py
> +        "../../../modules/common/prbs_gen/",
Please use the root Manifest.py here only. Make sure that both `prbs_gen` and `prbs_for_sys_id` are in the `modules/common/Manifest.py` file.

2023-03-29 20:29 UTC, Palmitoxico commented on modules/common/prbs_for_sys_id/prbs_gen_for_sys_id.vhd
> +    -- Enable
Please specify what this `en_i` does exactly.

2023-03-30 13:03 UTC, guilhermerc commented
All requested changes were addressed.

2023-03-30 13:19 UTC, Palmitoxico approved these changes

2023-03-30 13:19 UTC, merged