[WIP] common/biquad: add core
lnls-dig/infra-cores pull request #24
Opened 2023-09-15 17:55 UTC by guilhermerc

A biquadratic filter implementation using its canonical form.

2023-09-21 18:48 UTC, guilhermerc commented on modules/common/ifc_common_pkg.vhd
> +  -- Type that wraps all internall biquads' coefficients (a0 = 1)
typo: internal

2023-11-07 16:47 UTC, augustofg requested changes

2023-11-07 16:47 UTC, augustofg commented on modules/common/biquad/biquad.vhd
> +  SIGNAL state : NATURAL RANGE 0 TO 3 := 0;
Use an enumerated type here for the state signal, it brings more clarity to the FSM code and sometimes can use a more optimised representation than a numeric counting sequence.

2023-11-07 16:47 UTC, augustofg commented on modules/common/biquad/biquad.vhd
> +  PORT (
I see no busy flag exposed here even though the core is not fully pipelined.

2023-11-07 16:47 UTC, augustofg commented on modules/common/biquad/biquad.vhd
> +        state <= 0;
I think `y_valid_o` should be set to '0' here also.

2023-11-07 16:47 UTC, augustofg commented on modules/common/biquad/biquad.vhd
> +  SIGNAL terms : t_terms(c_AUX_B_IDX DOWNTO c_B0_TIMES_W_IDX)
Question: Why declare an array of terms and named indexes instead of simply declaring each term individually? This seems to me an unnecessary layer of indirection.

2023-11-07 16:47 UTC, augustofg commented on modules/common/ifc_common_pkg.vhd
> +USE ieee.fixed_pkg.ALL;
Please keep case consistency for the reserve words here.

2023-11-16 12:09 UTC, guilhermerc commented on modules/common/biquad/biquad.vhd
> +  SIGNAL state : NATURAL RANGE 0 TO 3 := 0;
The reason I used a numeric type here is that the states individually don't have cohesive meaning. They're simply operations done as soon as the operands are ready.

2023-11-16 12:22 UTC, guilhermerc commented on modules/common/biquad/biquad.vhd
> +        state <= 0;
You're right.

2023-11-16 13:24 UTC, guilhermerc commented on modules/common/biquad/biquad.vhd
> +  SIGNAL terms : t_terms(c_AUX_B_IDX DOWNTO c_B0_TIMES_W_IDX)
I don't see why this is a layer of indirection as `terms` isn't a "proxy signal". I did this bc I wanted to group all internal terms in this abstract type (for the sake of code organization). But I do agree this ain't helping much.

2023-11-16 17:38 UTC, guilhermerc commented on modules/common/biquad/biquad.vhd
> +  SIGNAL state : NATURAL RANGE 0 TO 3 := 0;
@augustofg can I keep it?

2023-11-16 17:56 UTC, augustofg commented on modules/common/biquad/biquad.vhd
> +  SIGNAL state : NATURAL RANGE 0 TO 3 := 0;
ok, you can.

2023-11-16 18:08 UTC, augustofg requested changes

2023-11-16 18:08 UTC, augustofg commented on modules/common/biquad/biquad.vhd
> +            busy_o <= '0';
The `busy_o` signal should be the result of a combinational operation of `x_valid_i` and `state`, otherwise it will be delayed an extra cycle.

2023-11-16 18:24 UTC, guilhermerc commented on modules/common/biquad/biquad.vhd
> +            busy_o <= '0';
Will it? The FSM cycles from 0 to 3 and in state 3 I assign `busy_o` to 0.

![image](https://github.com/lnls-dig/infra-cores/assets/22827202/d0a0303e-927b-4432-9ace-e5928670c58d)

2023-11-29 15:38 UTC, guilhermerc commented on modules/common/biquad/biquad.vhd
> +            busy_o <= '0';
As we talked in person, this is the correct `busy_o` flag behavior.

![image](https://github.com/lnls-dig/infra-cores/assets/22827202/d3144ea3-abac-48e3-bd14-20abf43f18d8)

2023-11-29 16:22 UTC, augustofg approved these changes

2023-11-29 16:22 UTC, merged